package com.project.skillforgebackend.ai.validation;

import com.project.skillforgebackend.ai.dto.AIEvaluationResponse;
import com.project.skillforgebackend.ai.dto.EvaluationItem;
import com.project.skillforgebackend.ai.dto.QuestionResponse;
import com.project.skillforgebackend.ai.exception.AIServiceException;
import com.project.skillforgebackend.quiz.entity.Question;
import com.project.skillforgebackend.quiz.entity.Quiz;
import org.springframework.stereotype.Component;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

/**
 * Post-parse structural validation of AI responses. The parsers guarantee
 * JSON/entity conversion; this step enforces contract-level invariants on
 * the semantic content:
 *
 * <ul>
 *   <li>Quiz: each question is typed and unique by {@code orderIndex}/{@code content}</li>
 *   <li>Evaluation: one verdict per quiz question, all IDs known, feedback present</li>
 * </ul>
 *
 * Failing validation surfaces as {@link AIServiceException} and triggers the
 * parse-retry budget in {@code AIService}, exactly like a JSON parse failure.
 */
@Component
public class AiResponseValidator {

    public void validateQuizQuestions(List<QuestionResponse> questions) {

        if (questions == null || questions.isEmpty()) {
            throw new AIServiceException(
                    "No questions were generated by AI."
            );
        }

        Set<Integer> orderIndexes = new HashSet<>();
        Set<String> contents = new HashSet<>();

        for (QuestionResponse question : questions) {

            if (question.getContent() == null
                    || question.getContent().isBlank()) {
                throw new AIServiceException(
                        "AI returned a question with empty content."
                );
            }

            if (question.getType() == null) {
                throw new AIServiceException(
                        "AI returned a question without a type."
                );
            }

            if (question.getType() == Question.QuestionType.MCQ) {

                if (question.getOptions() == null
                        || question.getOptions().size() != 4) {
                    throw new AIServiceException(
                            "MCQ must contain exactly 4 options."
                    );
                }
            }

            if (question.getOrderIndex() != null) {

                if (!orderIndexes.add(question.getOrderIndex())) {

                    throw new AIServiceException(
                            "AI generated duplicate orderIndex: "
                                    + question.getOrderIndex()
                                    + "."
                    );
                }
            }

            if (!contents.add(question.getContent())) {

                throw new AIServiceException(
                        "AI generated duplicate questions."
                );
            }
        }
    }

    /**
     * Every quiz question must be evaluated exactly once, every reported
     * question ID must belong to the quiz, and feedback must not be empty.
     */
    public void validateEvaluationCoverage(AIEvaluationResponse response, Quiz quiz) {

        List<Question> questions = quiz.getQuestions();

        if (questions == null || questions.isEmpty()) {
            return;
        }

        Set<UUID> quizIds = questions.stream()
                .map(Question::getId)
                .collect(java.util.stream.Collectors.toSet());

        Set<UUID> evaluated = new HashSet<>();

        List<EvaluationItem> evaluations =
                response.getEvaluations() == null
                        ? List.of()
                        : response.getEvaluations();

        for (EvaluationItem item : evaluations) {

            UUID id = item.getQuestionId();

            if (id == null) {
                throw new AIServiceException(
                        "AI evaluation contains a question without an ID."
                );
            }

            if (!quizIds.contains(id)) {

                throw new AIServiceException(
                        "AI evaluation references unknown question: " + id + "."
                );
            }

            if (!evaluated.add(id)) {

                throw new AIServiceException(
                        "AI evaluated question twice: " + id + "."
                );
            }

            if (item.getIsCorrect() == null) {

                throw new AIServiceException(
                        "AI evaluation is missing isCorrect for question " + id + "."
                );
            }

            if (item.getFeedback() == null || item.getFeedback().isBlank()) {

                throw new AIServiceException(
                        "AI evaluation is missing feedback for question " + id + "."
                );
            }
        }

        if (evaluated.size() < quizIds.size()) {

            throw new AIServiceException(
                    "AI evaluation is missing "
                            + (quizIds.size() - evaluated.size())
                            + " question evaluation(s)."
            );
        }
    }
}