# Application Name
spring.application.name=skillforge-backend

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/skillforge}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Sandip@6549}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# ==========================
# Flyway
# ==========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ==========================
# Server
# ==========================
server.port=8080

# ==========================
# JWT Configuration
# ==========================
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5VGhhdElzQXRMZWFzdDMyQnl0ZXNMb25nIQ==
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000

# ==========================
# OpenAI Configuration
# ==========================
openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-4o
openai.max-tokens=2000

# ==========================
# Logging
# ==========================
logging.level.com.learningplatform=DEBUG
logging.level.org.springframework.security=INFO

spring.profiles.active=dev