package com.project.skillforgebackend.ai.parser;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.project.skillforgebackend.ai.dto.AIQuizResponse;
import com.project.skillforgebackend.ai.exception.AIServiceException;
import com.project.skillforgebackend.ai.mapper.AIQuestionMapper;
import com.project.skillforgebackend.ai.validation.AiResponseValidator;
import com.project.skillforgebackend.quiz.entity.Question;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class QuizParser {

    private final ObjectMapper objectMapper;

    private final AIQuestionMapper questionMapper;

    private final AiResponseValidator responseValidator;

    /**
     * Parse AI generated quiz response.
     */
    public List<Question> parse(String json) {

        try {

            AIQuizResponse response = objectMapper.readValue(
                    ParserUtils.cleanJson(json),
                    AIQuizResponse.class
            );

            if (response == null
                    || response.getQuestions() == null
                    || response.getQuestions().isEmpty()) {

                throw new AIServiceException(
                        "No questions were generated by AI."
                );
            }

            responseValidator.validateQuizQuestions(response.getQuestions());

            List<Question> questions = response.getQuestions()
                    .stream()
                    .filter(question ->
                            question.getContent() != null
                                    && !question.getContent().isBlank()
                                    && question.getCorrectAnswer() != null
                                    && !question.getCorrectAnswer().isBlank()
                    )
                    .map(questionMapper::toEntity)
                    .toList();

            if (questions.isEmpty()) {

                throw new AIServiceException(
                        "AI returned JSON but no valid questions could be parsed."
                );

            }

            return questions;

        } catch (AIServiceException ex) {

            throw ex;

        } catch (Exception ex) {

            throw new AIServiceException(
                    "Failed to parse AI quiz response.",
                    ex
            );
        }

    }

}