import { motion } from "framer-motion";
import {
  Brain,
  FolderHeart,
  LineChart,
  Route,
  Sparkles,
  BellRing,
} from "lucide-react";

import SectionHeading from "../components/SectionHeading";
import { staggerContainer, staggerItem } from "@/lib/motion";

const FEATURES = [
  {
    icon: Brain,
    title: "AI practice, not AI content",
    body: "Quizzes generated on demand from the topics you're actually learning — with instant evaluation and per-question feedback from the model.",
    accent: "bg-ember/12 text-ember",
  },
  {
    icon: Route,
    title: "Structured learning paths",
    body: "A 12-week roadmap with week-by-week topics, resources, and goals — generated by AI, owned by you, adjustable anytime.",
    accent: "bg-aurora/12 text-aurora",
  },
  {
    icon: LineChart,
    title: "Learning health score",
    body: "A single 0–100 health score combining study time, quiz performance, and consistency — plus topic-by-topic mastery breakdowns.",
    accent: "bg-success/12 text-success",
  },
  {
    icon: FolderHeart,
    title: "Bookmarks that stay organized",
    body: "Folders, instant capture, and one-click revisit. Your curated library across topics, always one tap away.",
    accent: "bg-chart-3/12 text-chart-3",
  },
  {
    icon: Sparkles,
    title: "Achievements with meaning",
    body: "Seven badges earned through real behavior — first quiz, perfect score, path completed — not hollow gamification.",
    accent: "bg-warning/12 text-warning",
  },
  {
    icon: BellRing,
    title: "Momentum that reaches you",
    body: "A weekly digest of what you finished, what's at risk, and what to pick up next — so progress never quietly dies.",
    accent: "bg-rose-500/12 text-rose-500",
  },
];

export default function FeaturesSection() {
  return (
    <section id="features" className="relative py-24 lg:py-32">
      <div className="mx-auto max-w-screen-2xl px-6 lg:px-10">
        <SectionHeading
          eyebrow="What you get"
          title="Everything to start. Everything to finish."
          description="SkillForge isn't another library of courses. It's the operating system for your self-directed learning — from the first search to the final badge."
        />

        <motion.div
          variants={staggerContainer}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-80px" }}
          className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-3"
        >
          {FEATURES.map(({ icon: Icon, title, body, accent }) => (
            <motion.div
              key={title}
              variants={staggerItem}
              className="card-hover group rounded-3xl border bg-card p-7"
            >
              <div
                className={`flex size-12 items-center justify-center rounded-2xl ${accent} transition-transform duration-300 group-hover:scale-110`}
              >
                <Icon className="size-6" />
              </div>
              <h3 className="mt-5 text-lg font-semibold">{title}</h3>
              <p className="mt-2.5 text-sm leading-relaxed text-muted-foreground">
                {body}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
